#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Sanitize $_SERVER variables that may contain CR/LF characters
// (injected by some hosting environments like Render.com)
foreach ($_SERVER as $key => $value) {
    if (is_string($value)) {
        $_SERVER[$key] = str_replace(["\r", "\n", "\t"], '', $value);
    }
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
